name: 'Clubhouse Release'
description: 'Create a formatted release in github from formatted commit messages'
inputs:
  ghToken:
    description: 'Github token'
    required: true
  chStoryUrl:
    description: 'Clubhouse URL (ie. https://app.clubhouse.io/org/story)'
  createChangelog:
    description: 'Would you like to generate a changelog for this release?'
    default: true
  tag:
    description: 'The git tag for the current release'
    required: true
  previousTag:
    description: 'The git tag of the previous release'
  prerelease:
    description: 'Should the release be created in the "prereleased" state?'
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
