name: 'Shortcut Release'
description: 'Create a formatted release in github from formatted commit messages'
inputs:
  ghToken:
    description: 'Github token'
    required: true
  chStoryUrl:
    description: 'Shortcut URL (ie. https://app.shortcut.com/org/story)'
  createChangelog:
    description: 'Would you like to generate a changelog for this release?'
    default: true
  tag:
    description: 'The git tag for the current release'
    required: true
  previousTag:
    description: 'The git tag of the most recent prior release'
  prerelease:
    description: 'Would you like the release be created in the "prereleased" state?'
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
