name: Test Action
on:
  push:
    tags:
      - '*'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: release
      - name: Test run
        uses: ./.github/actions/release
